name: pill_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  #image_picker: ^1.1.0
  path_provider: ^2.1.2
  path: ^1.9.0
  intl: ^0.18.1
  table_calendar: ^3.0.9
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  graphql: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/test_foto.png
    - assets/Logo.png
    - assets/smartpill_homepage.png

